### ISSUE TITLE
Proxy fails on https://nitreb-forms.theismailiusa.org

### ISSUE THREAD

**Issue by abbasvalliani** [chhsiao90/nitmproxy#103]
Proxy is unable to process https://nitreb-forms.theismailiusa.org. The certificate chain is fine with no issues.

**Comment by abbasvalliani** [comment]
The website has some certificate related error. See below when replicated via JAVA directly. 

```
import java.net.*;
import java.io.*;
import javax.net.ssl.*;

/*
 * This example demostrates how to use a SSLSocket as client to
 * send a HTTP request and get response from an HTTPS server.
 * It assumes that the client is not behind a firewall
 */

public class SSLSocketClient {

    public static void main(String[] args) throws Exception {
	try {
	    SSLSocketFactory factory =
				      (SSLSocketFactory)SSLSocketFactory.getDefault();
	    SSLSocket socket =
			      (SSLSocket)factory.createSocket("nitreb-forms.theismailiusa.org", 443);

	    /*
             * send http request
             *
             * Before any application data is sent or received, the
             * SSL socket will do SSL handshaking first to set up
             * the security attributes.
             *
             * SSL handshaking can be initiated by either flushing data
             * down the pipe, or by starting the handshaking by hand.
             *
             * Handshaking is started manually in this example because
             * PrintWriter catches all IOExceptions (including
             * SSLExceptions), sets an internal error flag, and then
             * returns without rethrowing the exception.
             *
             * Unfortunately, this means any error messages are lost,
             * which caused lots of confusion for others using this
             * code.  The only way to tell there was an error is to call
             * PrintWriter.checkError().
             */
	    socket.startHandshake();

	    PrintWriter out = new PrintWriter(
					      new BufferedWriter(
		new OutputStreamWriter(
				       socket.getOutputStream())));

	    out.println("GET / HTTP/1.0");
	    out.println();
	    out.flush();

	    /*
             * Make sure there were no surprises
             */
	    if (out.checkError())
		System.out.println(
				   "SSLSocketClient:  java.io.PrintWriter error");

	    /* read response */
	    BufferedReader in = new BufferedReader(
		new InputStreamReader(
				      socket.getInputStream()));

	    String inputLine;
	    while ((inputLine = in.readLine()) != null)
		System.out.println(inputLine);

	    in.close();
	    out.close();
	    socket.close();

	} catch (Exception e) {
	    e.printStackTrace();
	}
    }
}
```

**Comment by abbasvalliani** [comment]
```
java SSLSocketClient
javax.net.ssl.SSLHandshakeException: received handshake warning: unrecognized_name
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:337)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:293)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:284)
        at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:272)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:186)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1408)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1314)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
        at SSLSocketClient.main(SSLSocketClient.java:40)
```

**Comment by chhsiao90** [comment]
I can connect the website with nitmproxy running `1.8.0_292`.

Can you provide the java version you are running?

**Comment by abbasvalliani** [comment]
I am using Java 11.

**Comment by chhsiao90** [comment]
I think the issue was caused by the SNI extension.

It looks like you are using the JDS built-in SSL library instead of openssl, which is not supporting SNI extension and cause the failure.

The [netty-tcnative](https://netty.io/wiki/forked-tomcat-native.html) must be included as a dependency while deploying the ntimproxy.
