### ISSUE TITLE
WebSockets not functional if response intercepted

### ISSUE THREAD

**Issue by abbasvalliani** [chhsiao90/nitmproxy#120]
Need to explore this more but looks like WebSockets are not functioning if HTTP2 responses are being intercepted. Will provide more details shortly.

**Comment by abbasvalliani** [comment]
@chhsiao90 This is big one. WebSockets are no longer functional with the release.

**Comment by abbasvalliani** [comment]
```
14:31:02.790 [nioEventLoopGroup-3-2] DEBUG c.g.c.nitmproxy.NitmProxyInitializer - [Client (kubernetes.docker.internal:61622)] <=> [PROXY] : connection init
14:31:02.798 [nioEventLoopGroup-3-2] DEBUG c.g.c.n.h.p.h.Http1FrontendHandler - [Client (kubernetes.docker.internal:61622)] <=> [PROXY] : handlerAdded
14:31:02.941 [nioEventLoopGroup-3-2] DEBUG c.g.c.n.h.p.tls.TlsBackendHandler - [Client (kubernetes.docker.internal:61622)] <=> [Server (live.chess.com:443)] : handlerAdded
14:31:02.977 [nioEventLoopGroup-3-2] DEBUG c.g.c.n.h.p.h.Http1FrontendHandler - [Client (kubernetes.docker.internal:61622)] <=> [Server (live.chess.com:443)] : DefaultFullHttpResponse(length=0)
14:31:03.004 [nioEventLoopGroup-3-2] DEBUG c.g.c.n.h.p.tls.TlsFrontendHandler - [Client (kubernetes.docker.internal:61622)] <=> [Server (live.chess.com:443)] : handlerAdded
14:31:03.010 [nioEventLoopGroup-3-2] DEBUG c.g.c.n.h.p.tls.TlsFrontendHandler - [Client (kubernetes.docker.internal:61622)] <=> [Server (live.chess.com:443)] : handlerRemoved
14:31:03.011 [nioEventLoopGroup-3-2] DEBUG c.g.c.n.h.p.h.Http1FrontendHandler - [Client (kubernetes.docker.internal:61622)] <=> [Server (live.chess.com:443)] : handlerRemoved
14:31:03.019 [nioEventLoopGroup-3-2] DEBUG c.g.c.n.h.p.tls.TlsFrontendHandler - SSL detection with true
14:31:03.023 [nioEventLoopGroup-3-2] DEBUG c.g.c.n.h.p.tls.TlsFrontendHandler - Client SNI lookup with live.chess.com
14:31:03.030 [nioEventLoopGroup-3-2] DEBUG c.g.c.n.h.p.tls.TlsFrontendHandler - Client ALPN lookup with null
14:31:03.130 [nioEventLoopGroup-3-2] DEBUG i.n.u.internal.NativeLibraryLoader - -Dio.netty.native.workdir: C:\Users\valli\AppData\Local\Temp (io.netty.tmpdir)
14:31:03.131 [nioEventLoopGroup-3-2] DEBUG i.n.u.internal.NativeLibraryLoader - -Dio.netty.native.deleteLibAfterLoading: true
14:31:03.131 [nioEventLoopGroup-3-2] DEBUG i.n.u.internal.NativeLibraryLoader - -Dio.netty.native.tryPatchShadedId: true
14:31:03.257 [nioEventLoopGroup-3-2] DEBUG i.n.u.internal.NativeLibraryLoader - Successfully loaded the library C:\Users\valli\AppData\Local\Temp\netty_tcnative_windows_x86_642322335641692384828.dll
14:31:03.259 [nioEventLoopGroup-3-2] DEBUG io.netty.handler.ssl.OpenSsl - Initialize netty-tcnative using engine: 'default'
14:31:03.259 [nioEventLoopGroup-3-2] DEBUG io.netty.handler.ssl.OpenSsl - netty-tcnative using native library: BoringSSL
14:31:03.382 [nioEventLoopGroup-3-2] DEBUG i.n.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@7c7efc
14:31:03.396 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 => ECDHE-ECDSA-AES128-GCM-SHA256
14:31:03.396 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 => ECDHE-ECDSA-AES128-GCM-SHA256
14:31:03.396 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 => ECDHE-RSA-AES128-GCM-SHA256
14:31:03.396 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_RSA_WITH_AES_128_GCM_SHA256 => ECDHE-RSA-AES128-GCM-SHA256
14:31:03.396 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 => ECDHE-ECDSA-AES256-GCM-SHA384
14:31:03.396 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 => ECDHE-ECDSA-AES256-GCM-SHA384
14:31:03.396 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 => ECDHE-RSA-AES256-GCM-SHA384
14:31:03.396 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_RSA_WITH_AES_256_GCM_SHA384 => ECDHE-RSA-AES256-GCM-SHA384
14:31:03.396 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 => ECDHE-ECDSA-CHACHA20-POLY1305
14:31:03.396 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 => ECDHE-ECDSA-CHACHA20-POLY1305
14:31:03.396 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 => ECDHE-RSA-CHACHA20-POLY1305
14:31:03.396 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 => ECDHE-RSA-CHACHA20-POLY1305
14:31:03.396 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256 => ECDHE-PSK-CHACHA20-POLY1305
14:31:03.396 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256 => ECDHE-PSK-CHACHA20-POLY1305
14:31:03.396 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA => ECDHE-ECDSA-AES128-SHA
14:31:03.396 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_ECDSA_WITH_AES_128_CBC_SHA => ECDHE-ECDSA-AES128-SHA
14:31:03.396 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA => ECDHE-RSA-AES128-SHA
14:31:03.396 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_RSA_WITH_AES_128_CBC_SHA => ECDHE-RSA-AES128-SHA
14:31:03.397 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA => ECDHE-PSK-AES128-CBC-SHA
14:31:03.397 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_PSK_WITH_AES_128_CBC_SHA => ECDHE-PSK-AES128-CBC-SHA
14:31:03.397 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA => ECDHE-ECDSA-AES256-SHA
14:31:03.397 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_ECDSA_WITH_AES_256_CBC_SHA => ECDHE-ECDSA-AES256-SHA
14:31:03.397 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA => ECDHE-RSA-AES256-SHA
14:31:03.397 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_RSA_WITH_AES_256_CBC_SHA => ECDHE-RSA-AES256-SHA
14:31:03.397 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA => ECDHE-PSK-AES256-CBC-SHA
14:31:03.397 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_PSK_WITH_AES_256_CBC_SHA => ECDHE-PSK-AES256-CBC-SHA
14:31:03.397 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_RSA_WITH_AES_128_GCM_SHA256 => AES128-GCM-SHA256
14:31:03.397 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_RSA_WITH_AES_128_GCM_SHA256 => AES128-GCM-SHA256
14:31:03.397 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_RSA_WITH_AES_256_GCM_SHA384 => AES256-GCM-SHA384
14:31:03.397 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_RSA_WITH_AES_256_GCM_SHA384 => AES256-GCM-SHA384
14:31:03.397 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_RSA_WITH_AES_128_CBC_SHA => AES128-SHA
14:31:03.397 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_RSA_WITH_AES_128_CBC_SHA => AES128-SHA
14:31:03.397 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_PSK_WITH_AES_128_CBC_SHA => PSK-AES128-CBC-SHA
14:31:03.397 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_PSK_WITH_AES_128_CBC_SHA => PSK-AES128-CBC-SHA
14:31:03.397 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_RSA_WITH_AES_256_CBC_SHA => AES256-SHA
14:31:03.397 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_RSA_WITH_AES_256_CBC_SHA => AES256-SHA
14:31:03.397 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_PSK_WITH_AES_256_CBC_SHA => PSK-AES256-CBC-SHA
14:31:03.397 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_PSK_WITH_AES_256_CBC_SHA => PSK-AES256-CBC-SHA
14:31:03.398 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_RSA_WITH_3DES_EDE_CBC_SHA => DES-CBC3-SHA
14:31:03.398 [nioEventLoopGroup-3-2] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_RSA_WITH_3DES_EDE_CBC_SHA => DES-CBC3-SHA
14:31:03.398 [nioEventLoopGroup-3-2] DEBUG io.netty.handler.ssl.OpenSsl - Supported protocols (OpenSSL): [SSLv2Hello, TLSv1, TLSv1.1, TLSv1.2, TLSv1.3] 
14:31:03.398 [nioEventLoopGroup-3-2] DEBUG io.netty.handler.ssl.OpenSsl - Default cipher suites (OpenSSL): [TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_CHACHA20_POLY1305_SHA256]
14:31:03.560 [nioEventLoopGroup-3-2] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x4503f758, L:/192.168.1.113:61645 - R:live.chess.com/207.97.242.140:443] HANDSHAKEN: protocol:TLSv1.3 cipher suite:TLS_AES_256_GCM_SHA384
14:31:03.561 [nioEventLoopGroup-3-2] DEBUG c.g.c.n.h.p.tls.TlsFrontendHandler - ALPN negotiated with http/1.1
14:31:04.226 [nioEventLoopGroup-3-2] DEBUG c.g.c.n.h.p.h.Http1BackendHandler - [Client (kubernetes.docker.internal:61622)] <=> [Server (live.chess.com:443)] : handlerAdded
14:31:04.234 [nioEventLoopGroup-3-2] DEBUG c.g.c.n.h.p.w.WebSocketBackendHandler - [Client (kubernetes.docker.internal:61622)] <=> [Server (live.chess.com:443)] : handlerAdded
14:31:04.253 [nioEventLoopGroup-3-2] DEBUG c.g.c.n.h.p.tls.TlsBackendHandler - [Client (kubernetes.docker.internal:61622)] <=> [Server (live.chess.com:443)] : handlerRemoved
14:31:04.257 [nioEventLoopGroup-3-2] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x2dedfc71, L:/127.0.0.1:8080 - R:/127.0.0.1:61622] HANDSHAKEN: protocol:TLSv1.3 cipher suite:TLS_AES_128_GCM_SHA256
14:31:04.257 [nioEventLoopGroup-3-2] DEBUG c.g.c.n.h.p.h.Http1FrontendHandler - [Client (kubernetes.docker.internal:61622)] <=> [Server (live.chess.com:443)] : handlerAdded
14:31:04.260 [nioEventLoopGroup-3-2] DEBUG c.g.c.n.h.p.w.WebSocketFrontendHandler - [Client (kubernetes.docker.internal:61622)] <=> [Server (live.chess.com:443)] : handlerAdded

```

**Comment by abbasvalliani** [comment]
@chhsiao90 I attached the log file. No interception here. live.chess.com which uses websocket is not functional. You can test it by going to [chess.com ](https://www.chess.com/play/online) and click play.

**Comment by x4A52** [comment]
Not sure whether this is the same issue, but outgoing WebSocket messages do not work for me either, Setting up the connection and receiving incoming messages works just fine. My case fails even if I use no interceptors (e.g. just straight up NitmProxy)

The problem exists with all WebSockets I tried, but it is most easily replicated by using the "Send Message" feature of https://echo.websocket.org/.ws

Any thoughts welcome. Thanks!

This is the TRACE log when sending message "TEST"

09:08:46.885 [nioEventLoopGroup-3-1] TRACE i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1
09:08:46.885 [nioEventLoopGroup-3-1] TRACE i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=4
09:08:46.885 [nioEventLoopGroup-3-1] DEBUG c.g.c.n.h.TailFrontendHandler - [Client (127.0.0.1:49450)] <=> [Server (echo.websocket.org:443)] : write TextWebSocketFrame(length=4) to server
09:08:46.886 [nioEventLoopGroup-3-1] TRACE i.n.h.c.h.w.WebSocket08FrameEncoder - Encoding WebSocket Frame opCode=1 length=4

Reading and decoding the message from the client works fine, but  an exception is thrown when the message is being encoded for writing it to the server. The exception is thrown in encodeNotHttpMessageContentTypes, when the message arrives with state == ST_INIT

    private void encodeNotHttpMessageContentTypes(ChannelHandlerContext ctx, Object msg, List<Object> out) {
        assert !(msg instanceof HttpMessage);
        if (state == ST_INIT) {
            try {
                if (msg instanceof ByteBuf && bypassEncoderIfEmpty((ByteBuf) msg, out)) {
                    return;
                }
                throwUnexpectedMessageTypeEx(msg, ST_INIT);
            } finally {
                ReferenceCountUtil.release(msg);
            }
        }


java.lang.IllegalStateException: unexpected message type: AdaptivePoolingAllocator$AdaptiveByteBuf, state: 0
	at io.netty.handler.codec.http.HttpObjectEncoder.throwUnexpectedMessageTypeEx(HttpObjectEncoder.java:369)
	at io.netty.handler.codec.http.HttpObjectEncoder.encodeNotHttpMessageContentTypes(HttpObjectEncoder.java:275)
	at io.netty.handler.codec.http.HttpObjectEncoder.encode(HttpObjectEncoder.java:189)
	at io.netty.handler.codec.http.HttpClientCodec$Encoder.encode(HttpClientCodec.java:290)
	at io.netty.handler.codec.http.HttpObjectEncoder.write(HttpObjectEncoder.java:105)
	at io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:344)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:825)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:752)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:827)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:752)
	at com.github.chhsiao90.nitmproxy.handler.protocol.ws.WebSocketBackendHandler.write(WebSocketBackendHandler.java:48)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:825)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:804)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:869)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1046)
	at io.netty.channel.Channel.writeAndFlush(Channel.java:257)
	at com.github.chhsiao90.nitmproxy.handler.TailFrontendHandler.channelRead(TailFrontendHandler.java:31)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:354)
	at com.github.chhsiao90.nitmproxy.handler.protocol.ws.WebSocketEventHandler.channelRead(WebSocketEventHandler.java:39)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:356)
	at com.github.chhsiao90.nitmproxy.handler.protocol.ws.WebSocketFrontendHandler.channelRead(WebSocketFrontendHandler.java:48)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:361)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:325)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1540)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1398)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1449)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:545)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:484)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1429)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:172)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.handle(AbstractNioChannel.java:445)
	at io.netty.channel.nio.NioIoHandler$DefaultNioRegistration.handle(NioIoHandler.java:388)
	at io.netty.channel.nio.NioIoHandler.processSelectedKey(NioIoHandler.java:596)
	at io.netty.channel.nio.NioIoHandler.processSelectedKeysOptimized(NioIoHandler.java:571)
	at io.netty.channel.nio.NioIoHandler.processSelectedKeys(NioIoHandler.java:512)
	at io.netty.channel.nio.NioIoHandler.run(NioIoHandler.java:484)
	at io.netty.channel.SingleThreadIoEventLoop.runIo(SingleThreadIoEventLoop.java:225)
	at io.netty.channel.SingleThreadIoEventLoop.run(SingleThreadIoEventLoop.java:196)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:1195)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
