### ISSUE TITLE
how to use ssl proxy mode?

### ISSUE THREAD

**Issue by SuiBianJun** [chhsiao90/nitmproxy#3]
hi, thanks your project. i am testing some function of your proxy. em, http proxy is good. but https proxy meet problems. i testing https by follow:
1、use openssl creat server.pem and key.pem.
2、proxy run in virtualmachine B, setting arguments before run proxy program.
3、a normal https server config in virtualmachine C as real server.
4、a normal client in virtualmachine A, use firefox, and setting ssl proxy address.

all config is ok, but when client request https page, proxy throw exception:

```
[main] INFO com.github.chhsiaoninety.nitmproxy.NitmProxy - NitmProxyConfig
proxyMode=HTTP
host=192.168.56.101
port=8080
httpsPorts=[443, 8443]
certFile=C:\p_server_cert_and_key\server_cert2.pem
keyFile=C:\p_server_cert_and_key\server2.pem
insecure=true
maxContentLength=1048576
clientHttp2=true
serverHttp2=true
nitmproxy is listened at http://192.168.56.101:8080
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - [Client (USER-20180608ZR:1107)] <=> [Server (null)] : handlerAdded
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - request method is connect, request: HttpObjectAggregator$AggregatedFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 0, widx: 0, cap: 0, components=0))
CONNECT safebrowsing.google.com:443 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 5.1; rv:32.0) Gecko/20100101 Firefox/32.0
Proxy-Connection: keep-alive
Connection: keep-alive
Host: safebrowsing.google.com:443
content-length: 0
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - handleTunnelProxyConnection method
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - tunnel adress: safebrowsing.google.com:443
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler - [PROXY] <=> [Server (safebrowsing.google.com:443)] : handlerAdded
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - [Client (USER-20180608ZR:1108)] <=> [Server (null)] : handlerAdded
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - request method is connect, request: HttpObjectAggregator$AggregatedFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 0, widx: 0, cap: 0, components=0))
CONNECT 192.168.56.200:443 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 5.1; rv:32.0) Gecko/20100101 Firefox/32.0
Proxy-Connection: keep-alive
Connection: keep-alive
Host: 192.168.56.200:443
content-length: 0
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - handleTunnelProxyConnection method
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - tunnel adress: 192.168.56.200:443
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler - [PROXY] <=> [Server (192.168.56.200:443)] : handlerAdded
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - [Client (USER-20180608ZR:1108)] <= [Proxy] : DefaultFullHttpResponse(decodeResult: success, version: HTTP/1.1, content: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 0, cap: 0))
HTTP/1.1 200 OK
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler - [Client (USER-20180608ZR:1108)] <=> [PROXY] : handlerAdded
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - [Client (USER-20180608ZR:1108)] <=> [Server (192.168.56.200:443)] : handlerRemoved
[nioEventLoopGroup-3-2] WARN io.netty.handler.ssl.ApplicationProtocolNegotiationHandler - [id: 0x227033f3, L:/192.168.56.101:49218 - R:/192.168.56.200:443] Failed to select the application-level protocol:
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
[nioEventLoopGroup-3-2] WARN io.netty.handler.ssl.ApplicationProtocolNegotiationHandler - [id: 0x227033f3, L:/192.168.56.101:49218 ! R:/192.168.56.200:443] TLS handshake failed:
java.nio.channels.ClosedChannelException
	at io.netty.handler.ssl.SslHandler.channelInactive(...)(Unknown Source)
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler - [PROXY] <=> [Server (192.168.56.200:443)] : handlerRemoved
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - [Client (USER-20180608ZR:1108)] <=> [Server (192.168.56.200:443)] : handlerAdded
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler - [Client (USER-20180608ZR:1108)] <=> [PROXY] : handlerRemoved
[nioEventLoopGroup-3-2] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: unknown_ca
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLException: Received fatal alert: unknown_ca
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:219)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at io.netty.handler.ssl.JdkSslEngine.unwrap(JdkSslEngine.java:90)
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:294)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1297)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	... 16 more
[nioEventLoopGroup-3-2] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: fatal SSLEngine condition
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:405)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:372)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1050)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLException: fatal SSLEngine condition
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1688)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:981)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at io.netty.handler.ssl.JdkSslEngine.unwrap(JdkSslEngine.java:90)
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:294)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1297)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	... 18 more
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
	at com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:571)
	at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1048)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:985)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491)
	at javax.crypto.Cipher.doFinal(Cipher.java:2377)
	at sun.security.ssl.CipherBox.decrypt(CipherBox.java:461)
	at sun.security.ssl.InputRecord.decrypt(InputRecord.java:172)
	at sun.security.ssl.EngineInputRecord.decrypt(EngineInputRecord.java:177)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:974)
	... 28 more
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - [Client (USER-20180608ZR:1108)] <=> [Server (192.168.56.200:443)] : handlerRemoved
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - [Client (USER-20180608ZR:1109)] <=> [Server (null)] : handlerAdded
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - request method is connect, request: HttpObjectAggregator$AggregatedFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 0, widx: 0, cap: 0, components=0))
CONNECT 192.168.56.200:443 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 5.1; rv:32.0) Gecko/20100101 Firefox/32.0
Proxy-Connection: keep-alive
Connection: keep-alive
Host: 192.168.56.200:443
content-length: 0
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - handleTunnelProxyConnection method
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - tunnel adress: 192.168.56.200:443
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler - [PROXY] <=> [Server (192.168.56.200:443)] : handlerAdded
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - [Client (USER-20180608ZR:1109)] <= [Proxy] : DefaultFullHttpResponse(decodeResult: success, version: HTTP/1.1, content: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 0, cap: 0))
HTTP/1.1 200 OK
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler - [Client (USER-20180608ZR:1109)] <=> [PROXY] : handlerAdded
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - [Client (USER-20180608ZR:1109)] <=> [Server (192.168.56.200:443)] : handlerRemoved
[nioEventLoopGroup-3-1] WARN io.netty.handler.ssl.ApplicationProtocolNegotiationHandler - [id: 0x4f4d9e6e, L:/192.168.56.101:49219 - R:/192.168.56.200:443] Failed to select the application-level protocol:
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
[nioEventLoopGroup-3-1] WARN io.netty.handler.ssl.ApplicationProtocolNegotiationHandler - [id: 0x4f4d9e6e, L:/192.168.56.101:49219 ! R:/192.168.56.200:443] TLS handshake failed:
java.nio.channels.ClosedChannelException
	at io.netty.handler.ssl.SslHandler.channelInactive(...)(Unknown Source)
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler - [PROXY] <=> [Server (192.168.56.200:443)] : handlerRemoved
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - [Client (USER-20180608ZR:1109)] <=> [Server (192.168.56.200:443)] : handlerAdded
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler - [Client (USER-20180608ZR:1109)] <=> [PROXY] : handlerRemoved
[nioEventLoopGroup-3-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 您的主机中的软件中止了一个已建立的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - [Client (USER-20180608ZR:1109)] <=> [Server (192.168.56.200:443)] : handlerRemoved
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - [Client (USER-20180608ZR:1110)] <=> [Server (null)] : handlerAdded
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - request method is connect, request: HttpObjectAggregator$AggregatedFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 0, widx: 0, cap: 0, components=0))
CONNECT 192.168.56.200:443 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 5.1; rv:32.0) Gecko/20100101 Firefox/32.0
Proxy-Connection: keep-alive
Connection: keep-alive
Host: 192.168.56.200:443
content-length: 0
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - handleTunnelProxyConnection method
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - tunnel adress: 192.168.56.200:443
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler - [PROXY] <=> [Server (192.168.56.200:443)] : handlerAdded
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - [Client (USER-20180608ZR:1110)] <= [Proxy] : DefaultFullHttpResponse(decodeResult: success, version: HTTP/1.1, content: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 0, cap: 0))
HTTP/1.1 200 OK
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler - [Client (USER-20180608ZR:1110)] <=> [PROXY] : handlerAdded
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - [Client (USER-20180608ZR:1110)] <=> [Server (192.168.56.200:443)] : handlerRemoved
[nioEventLoopGroup-3-2] WARN io.netty.handler.ssl.ApplicationProtocolNegotiationHandler - [id: 0x49de126e, L:/192.168.56.101:49220 - R:/192.168.56.200:443] Failed to select the application-level protocol:
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
[nioEventLoopGroup-3-2] WARN io.netty.handler.ssl.ApplicationProtocolNegotiationHandler - [id: 0x49de126e, L:/192.168.56.101:49220 ! R:/192.168.56.200:443] TLS handshake failed:
java.nio.channels.ClosedChannelException
	at io.netty.handler.ssl.SslHandler.channelInactive(...)(Unknown Source)
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler - [PROXY] <=> [Server (192.168.56.200:443)] : handlerRemoved
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - [Client (USER-20180608ZR:1110)] <=> [Server (192.168.56.200:443)] : handlerAdded
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler - [Client (USER-20180608ZR:1110)] <=> [PROXY] : handlerRemoved
[nioEventLoopGroup-3-2] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 您的主机中的软件中止了一个已建立的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
[nioEventLoopGroup-3-2] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - [Client (USER-20180608ZR:1110)] <=> [Server (192.168.56.200:443)] : handlerRemoved
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - [Client (USER-20180608ZR:1107)] <=> [Server (safebrowsing.google.com:443)] : handlerRemoved
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler - [PROXY] <=> [Server (safebrowsing.google.com:443)] : handlerRemoved
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - [Client (USER-20180608ZR:1111)] <=> [Server (null)] : handlerAdded
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - request method is connect, request: HttpObjectAggregator$AggregatedFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 0, widx: 0, cap: 0, components=0))
CONNECT safebrowsing.google.com:443 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 5.1; rv:32.0) Gecko/20100101 Firefox/32.0
Proxy-Connection: keep-alive
Connection: keep-alive
Host: safebrowsing.google.com:443
content-length: 0
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - handleTunnelProxyConnection method
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler - tunnel adress: safebrowsing.google.com:443
[nioEventLoopGroup-3-1] INFO com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler - [PROXY] <=> [Server (safebrowsing.google.com:443)] : handlerAdded
```
i use wireshark to catch process of ssl handshake, maybe after client send Encrypted Alert, proxy reponse Change Cipher Spec, Hello Request, Hello Request. and handshake finish. 

i don not kown what cause this exception, can you give me some advice? 
thanks.

**Comment by chhsiao90** [comment]
Any error log you can get on your server `192.168.56.200`?
It looks like this server close the connection.

**Comment by SuiBianJun** [comment]
thanks for your reply.
real server 192.168.56.200 use iis(win server 2008 r2) build website, in log, i just look some simple message like:
`#Software: Microsoft Internet Information Services 7.5
#Version: 1.0
#Date: 2018-12-07 06:19:59
#Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) sc-status sc-substatus sc-win32-status time-taken
2018-12-07 06:19:59 192.168.56.200 GET / - 443 - 192.168.56.103 Mozilla/5.0+(Windows+NT+5.1;+rv:32.0)+Gecko/20100101+Firefox/32.0 200 0 0 1359
2018-12-07 06:19:59 192.168.56.200 GET /favicon.ico - 443 - 192.168.56.103 Mozilla/5.0+(Windows+NT+5.1;+rv:32.0)+Gecko/20100101+Firefox/32.0 404 0 2 46
2018-12-07 06:19:59 192.168.56.200 GET /favicon.ico - 443 - 192.168.56.103 Mozilla/5.0+(Windows+NT+5.1;+rv:32.0)+Gecko/20100101+Firefox/32.0 404 0 2 109` 

even do not have message for proxy server(192.168.56.101), i not siminar.

maybe, the proxy server use ALPN for ssl handshake. i look client's wireshark packet, no message for ALPN negotiation, then i change a client os and broswer, client and proxy server ssl handshake look be ok. 

but real server just receive a packet of Client Hello message send by proxy, and no more :(.

oh, you are right, maybe between proxy and real server connection have problem, now i testing this process and reviewing code. thanks.

**Comment by SuiBianJun** [comment]
oh, https proxy now is ok. the problem is browser not believe server cert.
