### ISSUE TITLE
I'm unable to access any https or http2 request.

### ISSUE THREAD

**Issue by ajaiswal595** [chhsiao90/nitmproxy#4]
I'm just able to access http websites.

But  when i'm trying to hit any https website i'm getting exception.

I have tried this website http://wallacefund.info/  and i'm getting this open in firefox.

But When i'm trying 

https://httpbin.org/get

It's kept on hanging and no response comming yet.

And Even we want to access 

https://nghttp2.org/httpbin/get       which is http2 server.

This is the log 

================================================================================================================================================
14:27:32.813 [nioEventLoopGroup-2-1] DEBUG i.n.h.l.LoggingHandler - [id: 0x6518b244, L:/127.0.0.1:7878] RECEIVED: [id: 0x74f68b51, L:/127.0.0.1:7878 - R:/127.0.0.1:57849]
14:27:32.815 [nioEventLoopGroup-3-9] INFO  c.g.c.n.h.p.h.Http1FrontendHandler - [Client (localhost:57849)] <=> [Server (null)] : handlerAdded
14:27:32.815 [nioEventLoopGroup-3-9] INFO  c.g.c.n.h.p.t.TlsHandler - [PROXY] <=> [Server (httpbin.org:443)] : handlerAdded
14:27:33.130 [nioEventLoopGroup-3-9] INFO  c.g.c.n.h.p.h.Http1FrontendHandler - [Client (localhost:57849)] <= [Proxy] : DefaultFullHttpResponse(decodeResult: success, version: HTTP/1.1, content: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 0, cap: 0))
HTTP/1.1 200 OK
14:27:33.130 [nioEventLoopGroup-3-9] INFO  c.g.c.n.h.p.t.TlsHandler - [Client (localhost:57849)] <=> [PROXY] : handlerAdded
14:27:33.130 [nioEventLoopGroup-3-9] INFO  c.g.c.n.h.p.t.TlsHandler - [Client (localhost:57849)] <=> [PROXY] : handlerRemoved
14:27:33.131 [nioEventLoopGroup-3-9] WARN  i.n.c.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.ChannelPipelineException: com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler.handlerAdded() has thrown an exception; removed.
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:617)
	at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:560)
	at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:497)
	at com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler$1.operationComplete(Http1FrontendHandler.java:125)
	at com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler$1.operationComplete(Http1FrontendHandler.java:1)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:306)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:341)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: java.io.FileNotFoundException: server.pem (No such file or directory)
	at com.github.chhsiaoninety.nitmproxy.tls.CertUtil.newCert(CertUtil.java:63)
	at com.github.chhsiaoninety.nitmproxy.tls.TlsUtil.ctxForServer(TlsUtil.java:34)
	at com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler.sslCtx(TlsHandler.java:60)
	at com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler.handlerAdded(TlsHandler.java:49)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
	... 19 common frames omitted
Caused by: java.io.FileNotFoundException: server.pem (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at com.github.chhsiaoninety.nitmproxy.tls.CertUtil.readPemFromFile(CertUtil.java:68)
	at com.github.chhsiaoninety.nitmproxy.tls.CertUtil.newCert(CertUtil.java:38)
	... 23 common frames omitted
14:27:33.131 [nioEventLoopGroup-3-9] INFO  c.g.c.n.h.p.h.Http1FrontendHandler - [Client (localhost:57849)] <=> [Server (httpbin.org:443)] : handlerRemoved
14:27:33.131 [nioEventLoopGroup-3-9] INFO  c.g.c.n.NitmProxyInitializer - [Client (localhost:57849)] => Unhandled inbound: PooledUnsafeDirectByteBuf(ridx: 0, widx: 517, cap: 1024)
14:27:33.571 [nioEventLoopGroup-3-9] DEBUG i.n.h.s.SslHandler - [id: 0xab258f59, L:/10.52.37.130:57851 - R:httpbin.org/54.172.95.6:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
14:27:33.571 [nioEventLoopGroup-3-9] INFO  c.g.c.n.h.p.h.Http1BackendHandler - [Client (localhost:57849)] <=> [Server (httpbin.org:443)] : handlerAdded
14:27:33.572 [nioEventLoopGroup-3-9] INFO  c.g.c.n.h.p.t.TlsHandler - [PROXY] <=> [Server (httpbin.org:443)] : handlerRemoved

================================================================================================================================================

I saw server.pem is missing

I created one server.pem and key.pem and placed in the root directory.

Even though that doesn't work for me.

I'm getting followng error after placing server.pem and key.pem file in root of nitmproxy.

================================================================================================================================================

14:32:03.625 [nioEventLoopGroup-3-1] INFO  c.g.c.n.h.p.h.Http1FrontendHandler - [Client (localhost:59628)] <= [Proxy] : DefaultFullHttpResponse(decodeResult: success, version: HTTP/1.1, content: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 0, cap: 0))
HTTP/1.1 200 OK
14:32:03.628 [nioEventLoopGroup-3-1] INFO  c.g.c.n.h.p.t.TlsHandler - [Client (localhost:59628)] <=> [PROXY] : handlerAdded
14:32:03.811 [nioEventLoopGroup-3-1] INFO  c.g.c.n.h.p.t.TlsHandler - [Client (localhost:59628)] <=> [PROXY] : handlerRemoved
14:32:03.813 [nioEventLoopGroup-3-1] WARN  i.n.c.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.ChannelPipelineException: com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler.handlerAdded() has thrown an exception; removed.
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:617)
	at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:560)
	at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:497)
	at com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler$1.operationComplete(Http1FrontendHandler.java:125)
	at com.github.chhsiaoninety.nitmproxy.handler.protocol.http1.Http1FrontendHandler$1.operationComplete(Http1FrontendHandler.java:1)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:306)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:341)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: java.lang.ClassCastException: org.bouncycastle.pkcs.PKCS10CertificationRequest cannot be cast to org.bouncycastle.cert.X509CertificateHolder
	at com.github.chhsiaoninety.nitmproxy.tls.CertUtil.newCert(CertUtil.java:63)
	at com.github.chhsiaoninety.nitmproxy.tls.TlsUtil.ctxForServer(TlsUtil.java:34)
	at com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler.sslCtx(TlsHandler.java:60)
	at com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsHandler.handlerAdded(TlsHandler.java:49)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
	... 19 common frames omitted
Caused by: java.lang.ClassCastException: org.bouncycastle.pkcs.PKCS10CertificationRequest cannot be cast to org.bouncycastle.cert.X509CertificateHolder
	at com.github.chhsiaoninety.nitmproxy.tls.CertUtil.newCert(CertUtil.java:38)
	... 23 common frames omitted
14:32:03.813 [nioEventLoopGroup-3-1] INFO  c.g.c.n.h.p.h.Http1FrontendHandler - [Client (localhost:59628)] <=> [Server (httpbin.org:443)] : handlerRemoved
14:32:03.816 [nioEventLoopGroup-3-1] INFO  c.g.c.n.NitmProxyInitializer - [Client (localhost:59628)] => Unhandled inbound: PooledUnsafeDirectByteBuf(ridx: 0, widx: 517, cap: 1024)
14:32:04.337 [nioEventLoopGroup-3-1] DEBUG i.n.h.s.SslHandler - [id: 0x419fb655, L:/10.52.37.130:59630 - R:httpbin.org/34.193.212.251:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
14:32:04.340 [nioEventLoopGroup-3-1] INFO  c.g.c.n.h.p.h.Http1BackendHandler - [Client (localhost:59628)] <=> [Server (httpbin.org:443)] : handlerAdded
14:32:04.342 [nioEventLoopGroup-3-1] INFO  c.g.c.n.h.p.t.TlsHandler - [PROXY] <=> [Server (httpbin.org:443)] : handlerRemoved

================================================================================================================================================

Both https and http2 don't work with the proxy.

could you please let me know that I can make it unsafe / or provide me a cert file which works for that.

**Comment by chhsiao90** [comment]
It should work now!
