### ISSUE TITLE
NullPointerException on Backend Channel Bootstrap

### ISSUE THREAD

**Issue by abbasvalliani** [chhsiao90/nitmproxy#56]
```
13:49:26.111 [nioEventLoopGroup-3-1] DEBUG c.g.c.n.h.p.tls.TlsFrontendHandler - [Client (kubernetes.docker.internal:56465)] <=> [PROXY] : handlerAdded
13:49:26.112 [nioEventLoopGroup-3-1] DEBUG c.g.c.n.h.p.tls.TlsFrontendHandler - SSL detection with true
13:49:26.112 [nioEventLoopGroup-3-1] DEBUG c.g.c.n.h.p.tls.TlsFrontendHandler - Client SNI lookup with null
13:49:26.112 [nioEventLoopGroup-3-1] ERROR c.g.c.n.h.p.tls.TlsFrontendHandler - [Client (kubernetes.docker.internal:56465)] <=> [PROXY] : exceptionCaught with null
java.lang.NullPointerException: null
	at com.github.chhsiao90.nitmproxy.channel.BackendChannelBootstrap.connect(BackendChannelBootstrap.java:20)
	at com.github.chhsiao90.nitmproxy.NitmProxyMaster.connect(NitmProxyMaster.java:50)
	at com.github.chhsiao90.nitmproxy.ConnectionContext.connect(ConnectionContext.java:102)
	at com.github.chhsiao90.nitmproxy.handler.protocol.tls.TlsFrontendHandler$ConnectToRemote.channelRead(TlsFrontendHandler.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:515)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:515)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by abbasvalliani** [comment]
I think I see the issue here.

**Comment by chhsiao90** [comment]
Sounds like it's not possible to get the target address in this case.
- Transparent proxy
- TLS
- No SNI

It looks like the only thing we can do is to provide more readable error message in this case, right?

**Comment by abbasvalliani** [comment]
Exactly. We just need to cleanup and warn with a reasonable error message.

**Comment by chhsiao90** [comment]
v1.3.3 just released!
