### ISSUE TITLE
Changing log categories for certain exceptions

### ISSUE THREAD

**Issue by abbasvalliani** [chhsiao90/nitmproxy#57]
This will happen all the time with the browser. Should we not change IOException's related to aborts as DEBUG vs ERROR/WARN?

```
13:45:55.404 [nioEventLoopGroup-3-9] ERROR c.g.c.n.h.p.tls.TlsFrontendHandler - [Client (kubernetes.docker.internal:58427)] <=> [Server (fonts.gstatic.com:443)] : exceptionCaught with An established connection was aborted by the software in your host machine
java.io.IOException: An established connection was aborted by the software in your host machine
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1134)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by chhsiao90** [comment]
Sounds good, we should treat the client abort exception with different logging level, the stacktrace is also unnecessary.

**Comment by abbasvalliani** [comment]
Makes sense @chhsiao90.

**Comment by abbasvalliani** [comment]
It may be easier for you to do it if possible. Also, would appreciate another release if that is okay!

**Comment by chhsiao90** [comment]
v1.3.3 just released!
