### ISSUE TITLE
IllegalStateException - Observed numerous times

### ISSUE THREAD

**Issue by abbasvalliani** [chhsiao90/nitmproxy#60]
```
09:23:53.569 [nioEventLoopGroup-3-8] DEBUG c.g.c.n.h.p.tls.TlsFrontendHandler - Client ALPN lookup with [h2, http/1.1]
09:23:53.576 [nioEventLoopGroup-3-8] DEBUG c.g.c.n.h.p.tls.TlsFrontendHandler - Client ALPN lookup with null
09:23:53.576 [nioEventLoopGroup-3-8] DEBUG c.g.c.n.h.p.tls.TlsFrontendHandler - [Client (kubernetes.docker.internal:62894)] <=> [Server (v10.events.data.microsoft.com:443)] : channelInactive
09:23:53.577 [nioEventLoopGroup-3-8] ERROR c.g.c.n.h.p.tls.TlsFrontendHandler - [Client (kubernetes.docker.internal:62894)] <=> [Server (v10.events.data.microsoft.com:443)] : exceptionCaught with java.lang.IllegalStateException: complete already: DefaultPromise@916fb3(success: [h2, http/1.1])
io.netty.handler.codec.DecoderException: java.lang.IllegalStateException: complete already: DefaultPromise@916fb3(success: [h2, http/1.1])
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:478)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:404)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:371)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:819)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: complete already: DefaultPromise@916fb3(success: [h2, http/1.1])
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:99)
	at com.github.chhsiao90.nitmproxy.handler.protocol.tls.TlsFrontendHandler$AlpnNegotiateHandler.lookup(TlsFrontendHandler.java:200)
	at com.github.chhsiao90.nitmproxy.handler.protocol.tls.AbstractAlpnHandler.lookup(AbstractAlpnHandler.java:109)
	at io.netty.handler.ssl.SslClientHelloHandler.select(SslClientHelloHandler.java:188)
	at io.netty.handler.ssl.SslClientHelloHandler.decode(SslClientHelloHandler.java:169)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
	... 18 common frames omitted

```

**Comment by chhsiao90** [comment]
Hi @abbasvalliani,

How frequently does this occur? I'm not able to reproduce this issue and find any issue in the source code. Thanks.
