### ISSUE TITLE
SSL/TLS Exception with a website... https://latinlexicon.org/

### ISSUE THREAD

**Issue by abbasvalliani** [chhsiao90/nitmproxy#93]
```
13:48:36.732 [nioEventLoopGroup-3-7] DEBUG c.g.c.n.h.p.h.Http1FrontendHandler - [Client (kubernetes.docker.internal:58258)] <=> [PROXY] : handlerAdded
13:48:36.737 [nioEventLoopGroup-3-7] DEBUG c.g.c.n.h.p.tls.TlsBackendHandler - [Client (kubernetes.docker.internal:58258)] <=> [Server (latinlexicon.org:443)] : handlerAdded
13:48:36.739 [nioEventLoopGroup-3-7] DEBUG c.g.c.n.h.p.h.Http1FrontendHandler - [Client (kubernetes.docker.internal:58258)] <=> [Server (latinlexicon.org:443)] : DefaultFullHttpResponse
13:48:36.739 [nioEventLoopGroup-3-7] DEBUG c.g.c.n.h.p.tls.TlsFrontendHandler - [Client (kubernetes.docker.internal:58258)] <=> [Server (latinlexicon.org:443)] : handlerAdded
13:48:36.740 [nioEventLoopGroup-3-7] DEBUG c.g.c.n.h.p.tls.TlsFrontendHandler - [Client (kubernetes.docker.internal:58258)] <=> [Server (latinlexicon.org:443)] : handlerRemoved
13:48:36.740 [nioEventLoopGroup-3-7] DEBUG c.g.c.n.h.p.h.Http1FrontendHandler - [Client (kubernetes.docker.internal:58258)] <=> [Server (latinlexicon.org:443)] : handlerRemoved
13:48:36.746 [nioEventLoopGroup-3-7] DEBUG c.g.c.n.h.p.tls.TlsFrontendHandler - SSL detection with true
13:48:36.746 [nioEventLoopGroup-3-7] DEBUG c.g.c.n.h.p.tls.TlsFrontendHandler - Client SNI lookup with latinlexicon.org
13:48:36.746 [nioEventLoopGroup-3-7] DEBUG c.g.c.n.h.p.tls.TlsFrontendHandler - Client ALPN lookup with [h2, http/1.1]
13:48:36.780 [nioEventLoopGroup-3-7] DEBUG i.n.h.s.ReferenceCountedOpenSslContext - verification of certificate failed
		      sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
		      at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
		      at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
		      at java.base/sun.security.validator.Validator.validate(Validator.java:264)
		      at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
		      at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
		      at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
		      at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:234)
		      at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:723)
		      at io.netty.internal.tcnative.CertificateVerifierTask.runTask(CertificateVerifierTask.java:36)
		      at io.netty.internal.tcnative.SSLTask.run(SSLTask.java:38)
		      at io.netty.handler.ssl.ReferenceCountedOpenSslEngine$3.run(ReferenceCountedOpenSslEngine.java:1447)
		      at io.netty.handler.ssl.SslHandler.runAllDelegatedTasks(SslHandler.java:1512)
		      at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1526)
		      at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1390)
		      at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1245)
		      at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1282)
		      at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
		      at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
		      at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
		      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		      at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		      at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		      at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
		      at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
		      at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
		      at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
		      at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
		      at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		      at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		      at java.base/java.lang.Thread.run(Thread.java:834)
		      Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
		      at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
		      at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
		      at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
		      at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
		      ... 34 common frames omitted
13:48:36.782 [nioEventLoopGroup-3-7] WARN  i.n.h.s.ApplicationProtocolNegotiationHandler - [id: 0x8d04bbdb, L:0.0.0.0/0.0.0.0:58217] TLS handshake failed:
    javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
    at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.handshakeException(ReferenceCountedOpenSslEngine.java:1845)
    at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:812)
    at java.base/javax.net.ssl.SSLEngine.wrap(SSLEngine.java:522)
    at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:1039)
    at io.netty.handler.ssl.SslHandler.wrapNonAppData(SslHandler.java:925)
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1403)
    at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1245)
    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1282)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
    at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
    at java.base/sun.security.validator.Validator.validate(Validator.java:264)
    at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
    at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
    at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
    at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:234)
    at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:723)
    at io.netty.internal.tcnative.CertificateVerifierTask.runTask(CertificateVerifierTask.java:36)
    at io.netty.internal.tcnative.SSLTask.run(SSLTask.java:38)
    at io.netty.handler.ssl.ReferenceCountedOpenSslEngine$3.run(ReferenceCountedOpenSslEngine.java:1447)
    at io.netty.handler.ssl.SslHandler.runAllDelegatedTasks(SslHandler.java:1512)
    at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1526)
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1390)
    ... 21 common frames omitted
    Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
    at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
    at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
    at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
    ... 34 common frames omitted
13:48:36.782 [nioEventLoopGroup-3-7] DEBUG c.g.c.n.h.p.tls.TlsFrontendHandler - ALPN negotiate failed with javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
13:48:36.783 [nioEventLoopGroup-3-7] DEBUG c.g.c.n.h.p.tls.TlsBackendHandler - [Client (kubernetes.docker.internal:58258)] <=> [Server (latinlexicon.org:443)] : channelInactive
13:48:36.783 [nioEventLoopGroup-3-7] DEBUG c.g.c.n.h.p.tls.TlsBackendHandler - [Client (kubernetes.docker.internal:58258)] <=> [Server (latinlexicon.org:443)] : handlerRemoved
13:48:36.783 [nioEventLoopGroup-3-7] DEBUG c.g.c.n.h.p.tls.TlsFrontendHandler - Client ALPN lookup with [h2, http/1.1]
13:48:36.784 [nioEventLoopGroup-3-7] DEBUG i.n.h.ssl.SslClientHelloHandler - Unexpected client hello packet: 1603010200010001fc0303a22f5a98894d617be0a8a7ffe1140e8c682faa34cc0f15ec57a52ec4c16bb891208d7a92d7215c817b0d0c42631aace8eddb7bc6f8d0c5dccd5550746d4ff56c2200204a4a130113021303c02bc02fc02cc030cca9cca8c013c014009c009d002f003501000193aaaa00000000001500130000106c6174696e6c657869636f6e2e6f726700170000ff01000100000a000a00081a1a001d00170018000b00020100002300000010000e000c02683208687474702f312e31000500050100000000000d0012001004030804040105030805050108060601001200000033002b00291a1a000100001d0020eb1ba601b28d9b1fa0a0dbc72cecad480abe324349c61190b6b42b775dd45579002d00020101002b000b0a7a7a0304030303020301001b00030200024469000500030268325a5a000100001500c3000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
    java.lang.IllegalStateException: complete already: DefaultPromise@11d850bb(success: [h2, http/1.1])
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:99)
    at com.github.chhsiao90.nitmproxy.handler.protocol.tls.TlsFrontendHandler$AlpnNegotiateHandler.lookup(TlsFrontendHandler.java:143)
			  at com.github.chhsiao90.nitmproxy.handler.protocol.tls.AbstractAlpnHandler.lookup(AbstractAlpnHandler.java:108)
			  at io.netty.handler.ssl.SslClientHelloHandler.select(SslClientHelloHandler.java:188)
			  at io.netty.handler.ssl.SslClientHelloHandler.decode(SslClientHelloHandler.java:149)
			  at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
			  at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
			  at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:404)
			  at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:371)
			  at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
			  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
			  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
			  at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
			  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
			  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
			  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
			  at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
			  at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831)
			  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
			  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
			  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
			  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
			  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
			  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
			  at java.base/java.lang.Thread.run(Thread.java:834)
13:48:36.784 [nioEventLoopGroup-3-7] DEBUG c.g.c.n.h.p.tls.TlsFrontendHandler - Client ALPN lookup with null
13:48:36.785 [nioEventLoopGroup-3-7] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
			  io.netty.handler.codec.DecoderException: java.lang.IllegalStateException: complete already: DefaultPromise@11d850bb(success: [h2, http/1.1])
			  at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:477)
			  at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:404)
			  at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:371)
			  at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
			  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
			  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
			  at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
			  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
			  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
			  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
			  at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
			  at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831)
			  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
			  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
			  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
			  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		    at java.base/java.lang.Thread.run(Thread.java:834)
		    Caused by: java.lang.IllegalStateException: complete already: DefaultPromise@11d850bb(success: [h2, http/1.1])
		    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:99)
		    at com.github.chhsiao90.nitmproxy.handler.protocol.tls.TlsFrontendHandler$AlpnNegotiateHandler.lookup(TlsFrontendHandler.java:143)
		    at com.github.chhsiao90.nitmproxy.handler.protocol.tls.AbstractAlpnHandler.lookup(AbstractAlpnHandler.java:108)
		    at io.netty.handler.ssl.SslClientHelloHandler.select(SslClientHelloHandler.java:188)
		    at io.netty.handler.ssl.SslClientHelloHandler.decode(SslClientHelloHandler.java:169)
		    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
		    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
		    ... 18 common frames omitted

```

**Comment by abbasvalliani** [comment]
@chhsiao90 I looked at this more. Not an issue with nitmproxy. The site has an intermediate certificate that cannot be found. The browser doesn't complain **_(why?)_** but there must be a way to only check the root certificate without checking the intermediate certificate. I think another approach is to prompt the user that the website has an invalid certificate and still allow them to continue. What are your thoughts on this? You can replicate this by running the following source code:

```
import java.net.*;
import java.io.*;
import javax.net.ssl.*;

/*
 * This example demostrates how to use a SSLSocket as client to
 * send a HTTP request and get response from an HTTPS server.
 * It assumes that the client is not behind a firewall
 */

public class SSLSocketClient {

    public static void main(String[] args) throws Exception {
	try {
	    SSLSocketFactory factory =
				      (SSLSocketFactory)SSLSocketFactory.getDefault();
	    SSLSocket socket =
			      (SSLSocket)factory.createSocket("www.latinlexicon.org", 443);

	    /*
             * send http request
             *
             * Before any application data is sent or received, the
             * SSL socket will do SSL handshaking first to set up
             * the security attributes.
             *
             * SSL handshaking can be initiated by either flushing data
             * down the pipe, or by starting the handshaking by hand.
             *
             * Handshaking is started manually in this example because
             * PrintWriter catches all IOExceptions (including
             * SSLExceptions), sets an internal error flag, and then
             * returns without rethrowing the exception.
             *
             * Unfortunately, this means any error messages are lost,
             * which caused lots of confusion for others using this
             * code.  The only way to tell there was an error is to call
             * PrintWriter.checkError().
             */
	    socket.startHandshake();

	    PrintWriter out = new PrintWriter(
					      new BufferedWriter(
		new OutputStreamWriter(
				       socket.getOutputStream())));

	    out.println("GET / HTTP/1.0");
	    out.println();
	    out.flush();

	    /*
             * Make sure there were no surprises
             */
	    if (out.checkError())
		System.out.println(
				   "SSLSocketClient:  java.io.PrintWriter error");

	    /* read response */
	    BufferedReader in = new BufferedReader(
		new InputStreamReader(
				      socket.getInputStream()));

	    String inputLine;
	    while ((inputLine = in.readLine()) != null)
		System.out.println(inputLine);

	    in.close();
	    out.close();
	    socket.close();

	} catch (Exception e) {
	    e.printStackTrace();
	}
    }
}
```

**Comment by chhsiao90** [comment]
I guessed the reason why browser doesn't complain about the certificate chain issue is that the intermediate certificate was already trusted by the browser.

We can check what makes the difference between the browser and the proxy first. After that, we can consider to have a whitelist for accepting insecure accessing (Currently, we already have an option `--insecure` to bypass all certificate issues, I'm not sure if it works in your use case)

**Comment by abbasvalliani** [comment]
Good point. @chhsiao90 . Even an external SSL check shows the missing root CA. It must be that the browser CA Root store must be more expansive than JAVA cacert but not sure.

I believe the best approach to handle this is the following:

Config Options:
1. NitmConfig should have 2 config methods.

```
//on invalid certificate, callback to client. Hostname can allow certificate wild cards.
boolean acceptCertificate(String hostname, String protocol, CertError code, CertDetails certificateDetails)

//if certificate is declined, an ability of the client to customize the return message to front end
void onInvalidCertificate(Provide the interceptor which can be either Http or Forward). The client can customize the return.

//white list of hostname exempted from certificate validation
void certificateExemptionHosts(List<String> hostname)

```
Therefore, 
1. Use untrusted SSL connection on the backend. Record certificate issues when encountered.
2. If the certificate is invalid (and the hostname is not in a whitelist which is available via NitmConfig) we provide a callback to the NitmProxy client (via Config) on the certificate issue, the underlying protocol (HTTP etc) and a simple return of accept or decline. 
3. The client can always decline the first time and then allow the user to add it to a whitelist and can make the call again 
4. The return can be customized by the client. For e.g we can show a warning message to continue. For button click, hostname is added to the whitelist.
 
I believe it provides an elegant solution. What do you think?

Abbas

**Comment by chhsiao90** [comment]
Sounds good to me  to have an interface for checking trusted certificates.

I guessed it should be sufficient to support this functionality with just `acceptCertificate`.

The `onInvalidCertificate` makes things more complicated, I will consider not having this feature at the first phase.

I think we don't need a `certificateExemptionHosts` function to support white list configuration. I guessed users are able to configure their white list easily even without this method.

I will have a draft quickly for supporting this feature.

**Comment by abbasvalliani** [comment]
Thanks @chhsiao90. Makes sense and thanks for looking into this. Without onInvalidCertificate, is there a way we can store the Certificate error in a context so an interceptor can access it? Basically, I want to be able to implement the flow of:

If there is a certificate error -> Brower Prompt of Certificate (Ignore Button) -> Continue connection if ignored

If the backend is connected, I can always use the interceptor to do the Browser Prompt.

**Comment by chhsiao90** [comment]
It's easy to provide an invalid certificate store. But I have a question about how would you correlate the http request with the invalid certificate store?

For example, browser might open 2 http connection to a website at the same time, how do we distinguish if one accepted the prompt, but the other is not?

I guessed maybe we should have connection context level interceptors or state to solve this issue. What do you think?

**Comment by abbasvalliani** [comment]
Good point @chhsiao90. It has to be at the connection level since SSL is stateful and only one handshake is done for multiple HTTP requests in a session. When the back end connects, we know the underlying protocol and the certificate issue encountered. 

**Option 1**
Perhaps the easiest solution would be to generate a handshake error if acceptCertificate returns false on the front end side. I don't know how the browser will display the error (I am assuming the handshake should allow us to send back a reasonable error code). The issue remains though which is the ability of the client to accept the certificate as part of the workflow but this is certainly better since the error is more descriptive. 
 

**Option 2**
 The other option is that if we detect that the protocol on the backend is HTTP1/2 and we allow the front end to send a custom HTTP response with an HTTP error (the back end should be closed). 

You're right that multiple requests will sent back with the same response back (which may be okay). The response will be via an interceptor. The link has to point to a URL back to proxy that adds the certificate wild card to the whitelist. Not clean and seems hacky but perhaps can be done gracefully. Once done, we can do a front-end redirect to the original URL. 

I am still not sure about the clean workflow, but we certainly need to have the ability for the client to override the certificate error.

**Comment by chhsiao90** [comment]
Hi @abbasvalliani 

I have an initial draft in #97

I will try to provide a implementation as below
1. When an insecure connection initiated, the InsecureAccessSupport will change the state to AccessSupport.ASK and accept the connection.
2. When the interceptor find the state is AccessSupport.ASK, it will send the response with a html page contains links for accept/deny the connection.
3. When the interceptor find the state is AccessSupport.ASK, and found the url contains the magic string, it will change the state to either AccessSupport.ACCEPT or AccessSupport.DENY

**Comment by chhsiao90** [comment]
Feature implemented. Example can be found [UnsafeAccess](https://github.com/chhsiao90/nitmproxy-examples/blob/master/src/main/java/com/github/chhsiao90/nitmproxy/examples/UnsafeAccess.java)

**Comment by abbasvalliani** [comment]
Thanks @chhsiao90. Will try it out tomorrow.

**Comment by abbasvalliani** [comment]
@chhsiao90 I am working on it today and while the prior website is now coming up, I am not getting the ask prompt. Could this be because I already have existing listeners in place?

**Comment by abbasvalliani** [comment]
I figured it out. Testing it now.

**Comment by abbasvalliani** [comment]
@chhsiao90 Works really well. Really appreciate it. Can we do a merge and release? Thank you!

**Comment by chhsiao90** [comment]
nitmproxy v1.5.0 just released with unsafe access support.
